name: auth-api-stack
services:
  auth-api-containers:
    image: 'postgres:15-alpine'
    container_name: 'usr_api_postgres'
    environment:
      - 'POSTGRES_DB=login-api-db'
      - 'POSTGRES_PASSWORD=secretpass'
      - 'POSTGRES_USER=api-user'
    ports:
      - '5432:5432'
#    volumes:
#      - 'docker_userservice-db:/var/lib/postgresql/data'
#volumes:
#  docker_userservice-db:
#    external: true
